export default {
  store: true,
  layouts: true,
  meta: true,
  middleware: true,
  transitions: true,
  deprecations: true,
  validate: true,
  asyncData: true,
  fetch: true,
  clientOnline: true,
  clientPrefetch: true,
  componentAliases: true,
  componentClientOnly: true,
}
